config/routes.rb
Blogmask::Application.routes.draw do

  root 'application#index'

  get '/about' => 'application#about'
  get '/contact' => 'application#contact'
  get '/browse' => 'application#browse'

  resources :posts

  post '/posts/:id/vote' => 'posts#vote', as: 'post_vote'

  get '/posts/category/:category' => 'posts#category', as: 'post_category'

  get 'posts/:id/signin' => 'posts#signin', as: 'post_signin'

  post 'posts/:id/authenticate' => 'posts#authenticate', as: 'post_authenticate'

  get 'posts/:id/:slug' => 'posts#show', as: 'post_slug'

  

end

app/models/post.rb
require 'base64'

class Post < ActiveRecord::Base
  has_secure_password

  def self.find_by_hashed_key(hashed)
    find(unhash_key(hashed))
  end

  def self.unhash_key(hashed)
    Base64.strict_decode64(hashed).to_i
  end

  def self.top_all_time(num)
    all.limit(num).order('numvotes DESC')
  end

  def self.top_last_week(num)
    where("lastvoted > ?", Time.now - 7.days).limit(10).order('numvotes DESC')
  end

  def hashed_key
    Base64.strict_encode64(id.to_s)
  end

  def title_slug
    title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
  end

  def body_preview
    stripped = body.gsub(/<[^>]+>/,' ').gsub('&nbsp', '').strip.squeeze(' ')
    if stripped.length <= 50
      stripped
    else
      stripped[0..50] + '...'
    end
  end

  def parent
    Post.find(parent_id) unless parent_id.nil?
  end

  def replies
    Post.where(parent_id: id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end

  def about
  end

  def contact
  end

  def browse
    @alltime = Post.top_all_time(10)
    @thisweek = Post.top_last_week(10)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  include Category

  def new
    @post = Post.new
    @parent = Post.find_by_hashed_key(params[:reply]) unless params[:reply].nil?
  end

  def create
    @post = Post.new(post_params)
    @post.password_confirmation = params[:post][:password]

    if @post.save
      flash[:success] = 'Post created!  Make sure to copy the link somewhere, you will need it to get back to your post.'
      redirect_to real_post_path(@post)
    else
      # TODO: Restore from LocalStorage
      flash[:alert] = 'Sorry! There was a problem creating your post.'
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find_by_hashed_key(params[:id])
  end

  def edit
    @post = Post.find_by_hashed_key(params[:id])

    if (!signed_in?(@post))
      flash[:notice] = 'Please sign in to edit.'
      redirect_to post_signin_path(@post.hashed_key)
    end
  end

  def update
    # TODO: Make the edit form send the hashed key
    @post = Post.find(params[:id])

    if !signed_in?(@post)
      redirect_to real_post_path(@post)
    end

    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.category = params[:post][:category]

    if @post.save
      flash[:success] = 'Post updated!'
    else
      flash[:alert] = 'Sorry! There was a problem editing your post.'
    end

    # Sign out on each edit
    sign_out
    redirect_to real_post_path(@post)
  end

  def vote
    @post = Post.find_by_hashed_key(params[:id])
    @post.increment(:numvotes, 1)
    @post.lastvoted = Time.now
    @post.save
    
    respond_to do |format|
      format.json { render text: 'Voted.' }
      format.html { redirect_to real_post_path(@post) }
    end
  end

  def category
    @category = params[:category]
    # TODO: pagination...
    @posts = Post.where(category: @category).limit(20).order('numvotes DESC')
  end 

  def signin
    @post = Post.find_by_hashed_key(params[:id])
  end

  def authenticate
    @post = Post.find_by_hashed_key(params[:id])
    if sign_in?(@post, params[:password])
      flash[:success] = 'Signed in!'
      redirect_to edit_post_path(@post.hashed_key)
    else
      flash[:alert] = 'Sorry, that password was not correct.'
      redirect_to post_signin_path(@post.hashed_key)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :password, :category, :parent_id)
  end

  def real_post_path(post)
    post_slug_path(post.hashed_key, post.title_slug)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def sign_in?(post, password)
    if post.authenticate(password)
      cookies.signed[:post_id] = post.id
      self.current_post = post
      return true;
    else
      return false;
    end
  end

  def current_post
    @current_post
  end

  def current_post=(post)
    @current_post = post
  end

  def signed_in?(post)
    (!post.nil? && (post.id == cookies.signed[:post_id]))
  end

  def sign_out
    cookies.delete(:post_id)
    self.current_post = nil
  end

end

app/views/application/about.html.erb
<h1>About BlogMask</h1>
<hr>

<h3>What is BlogMask</h3>
<p>
  BlogMask is the simplest way to make an anonymous blog post and share it on the internet.  You don't need an account, or even an email address.  Just write, and then share the link.
</p>

<h3>Why would I use BlogMask?  I already have a WordPress/Blogger/Facebook/etc.</h3>
<p>
  Sometimes you just want to say something online, and you don't want it associated with your identity.  Maybe you want to write about a former employer, but don't want to put it on your blog.  Maybe you have some controversial opinions that are better left anonymous.  Or maybe you want to get an honest reaction to a blog post that has nothing to do with who you are.  Privacy is harder to come by every day, BlogMask is for those times when you just want to write off the record.
</p>

<h3>How is BlogMask Anonymous?</h3>
<p>
  We don't store anything about who posts, and we don't track you in any way.  This way, we don't even know who wrote any given post.  Posts are just stored as formatted text and are accessible through a public link.
</p>

<h3>If there are no accounts, how do I control my post?</h3>
<p>
  When you write a post, you set a post-specific password.  At the bottom of any post you will see a link to edit it, which will require entering the password you set.  Make sure to protect this password!  Because we don't track user information, anyone with the password can edit your post just as you can.
</p>

<h3>Who pays for BlogMask</h3>
<p>
  I (Sam) pay to host and maintain BlogMask.  I'll keep it running as long as I can.  If you'd like to donate to support BlogMask, you can do so anonymously using the BitCoin address at the bottom of the page.
</p>

app/views/application/browse.html.erb
<h1>Browse</h1>
<hr>

<h2>By Category</h2>
<% Category.all.each_slice(4) do |slice| %>
  <div class="row p5">
    <% slice.each do |c| %>
      <div class="large-3 small-3 columns cat-col">
        <%= link_to c, post_category_path(c) %>
      </div>
    <% end %>
  </div>
<% end %>

<hr>

<h2>Top Posts</h2>
<div class="row">

  <div class="large-6 small-6 columns">
    <h3>Top This Week</h3>
    <% @thisweek.each do |p| %>
      <div class="panel hide-over">
        <%= render partial: 'posts/title_and_score', locals: { post: p } %>
      </div>
    <% end %>
  </div>

  <div class="large-6 small-6 columns">
    <h3>Top All Time</h3>
    <% @alltime.each do |p| %>
      <div class="panel hide-over">
        <%= render partial: 'posts/title_and_score', locals: { post: p } %>
      </div>
    <% end %>
  </div>

</div>

app/views/application/contact.html.erb
<h1>Contact BlogMask</h1>
<hr>
<div>
  If you have any questions, comments, or concerns about BlogMask please contact Sam at
  <b>sam [at] habosa [dot] com</b>.  Feel free to reach out, for any reason or if you spot a bug on the site.
</div>

app/views/application/index.html.erb
<h1>Welcome to BlogMask</h1>
<h3 class="subheader">
  An <b class="dotted-under">anonymous blogging</b> service, for when you just want to say what's on your mind.
  <br />
  <b class="dotted-under">No accounts.</b>  No email address.  <b class="dotted-under">Just write</b>, share, and discuss.
</h3>

<br />
<h4>It's easy to get started:</h4>

<p>
  <div class="t-inline list-circle dotted">1</div>
  <div class="t-inline list-content">
    Write a post.  Say whatever you want.
  </div>
</p>

<p>
  <div class="t-inline list-circle dotted">2</div>
  <div class="t-inline list-content">
    Set a password for the post so you can edit it later.
  </div>
</p>

<p>
  <div class="t-inline list-circle dotted">3</div>
  <div class="t-inline list-content">
    Get a link, share it with the world.
  </div>
</p>

<h2>Ready?</h2>
<a href="<%= new_post_path %>" class="button success">Start Writing</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>BlogMask</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <!-- data attributes are for LoadJS gem -->
  <body 
    data-controller="<%= controller.controller_path %>" 
    data-action="<%= controller.action_name %>">

    <!-- Top Navigation Bar -->
  	<nav class="top-bar" data-topbar>
  		<ul class="title-area">
  			<li class="name">
  				<h1><a href="/">BlogMask</a></h1>
  			</li>
  		</ul>

      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><a href="/browse">Browse</a></li>

          <li class="divider"></li>
          <li><a href="/about">About</a></li>

          <li class="divider"></li>
          <li><a href="/contact">Contact</a></li>

          <li class="divider"></li>
          <li class="has-form">
            <a href="<%= new_post_path %>" class="small button">New Post</a>
          </li>
        </ul>
      </section>
  	</nav>

    <!-- Flash Messages -->
    <div class="row" id="flash-row">
        <% flash.each do |k, v| %>
          <div class="alert-box <%= k %>"><%= v %></div>
        <% end %>
    </div>

    <!-- Main Body -->
    <section role="main">
      <div class="row">
        <!-- Center Content -->
        <div class="large-12 columns" id="main-content">
          <%= yield %>
        </div>
        <hr>
        <div class="large-12 columns" id="footer-content">
            <div class="panel">
              <b>BTC Donations: </b>
              <pre style="display: inline; margin-left: 10px;">1ABiogo1FBiPTjRuetnUQrf1HaitqiLj3S</pre>
              <a href="/assets/bitcoin.png">(QR)</a>
            </div>
        </div>
      </div>
    </section>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_post_editor.html.erb
<h1 id="hallo-title" class="dotted editor title-editor" contenteditable>
  <%= raw(title) %>
</h1>

<div id="hallo-editor-parent">
  <div id="hallo-toolbar"></div>
  <div id="hallo-editor" class="dotted editor body-editor">
    <%= raw(body) %>
  </div>
  <br />
</div>

<%= form_for(@post, :html => { :style => 'display:inline;' }) do |f| %>
  <%= f.hidden_field :title, :id => 'h-title-field', :value => title %>
  <%= f.hidden_field :body , :id => 'h-body-field', :value => body %>
  <% unless @parent.nil? %>
    <%= f.hidden_field :parent_id, :value=> parent.id %>
  <% end %>

  <%= f.label :category, 'Category: ' %>
  <%= f.select :category, Category.all
  %>
  <br />

  <% if password == true %>
    <%= f.label :password, 'Password: ' %>
    <%= f.password_field :password, :id => 'password-field', :placeholder => 'post password (required)' %>
    <span class="gen-form-elm" style="color: red; margin-left: 5px;">*</span>
    <br />
  <% end %>

  <a href="#"  id="preview-button" class="button">Toggle Preview</a>
  <%= f.submit :value => 'Save Post', :class => 'button success', :id => 'submit-button' %>
<% end %>

app/views/posts/_title_and_score.html.erb
<div class="t-inline list-circle dotted">
  +<%= post.numvotes %>
</div>
<div class="t-inline list-content v-middle">
    <div class="no-over mb">
      <b><%= link_to post.title, 
        post_slug_path(post.hashed_key, 
        post.title_slug) %></b>
    </div>
    <div class="no-over">
      <%= raw(post.body_preview) %>
    </div>
</div>

app/views/posts/category.html.erb
<h1><%= @category %></h1>
<hr>
<% if (@posts.count == 0) %>
  Sorry, there are no posts for this category yet.  
  Why not <%= link_to "write one", new_post_path %>?
<% else %>
  <% @posts.each do |post| %>
    <div class="panel small-11 large-9 small-centered columns">
      <div class="post-preview">
        <%= render partial: 'title_and_score', locals: { post: post } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<hr>

<%= render :partial => 'post_editor', :locals => 
  { :title => @post.title, 
    :body => @post.body,
    :password => false,
    :parent => nil } %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<h5 class="subheader">
  Just start writing.  What you see is what you get.
</h5>

<hr>
<% unless @parent.nil? %>
  <h6 class="gen-form-elm">Replying to: 
  <%= link_to @parent.title, 
              post_slug_path(@parent.hashed_key, 
              @parent.title_slug) %></h6>
<% end %>
<%= render :partial => 'post_editor', :locals => 
  { :title => "Post Title", 
    :body => "Say what's on your mind",
    :password => true,
    :parent => @parent } %>

app/views/posts/show.html.erb
<div class="post-body">

  <!-- Kudo Vote Widget -->
  <figure class="kudo kudoable" id="kudo-vote" data-id="<%= @post.hashed_key %>">
    <a class="kudobject" style="margin-bottom: 5px;">
        <div class="opening">
            <div class="circle">&nbsp;</div>
        </div>
    </a>
    <a href="#kudo" class="count">
        <span class="num" style="display: inline;"><%= @post.numvotes %></span>
        <span class="txt" style="display: inline;">Points</span>
    </a>
  </figure>

  <!-- Post Category Label -->
  <a href="<%= post_category_path(@post.category) %>" class="cat-label button small success">Category: <%= @post.category %></a>

  <!-- Parent Label -->
  <% unless @post.parent.nil? %>
    <%= link_to 'Parent Post', 
                post_slug_path(
                  @post.parent.hashed_key, 
                  @post.parent.title_slug),
                class: 'cat-label button small' %>
  <% end %>
  <br />

  <!-- Post title and edit button -->
  <h1 style="display: inline;">
    <%= @post.title %>
  </h1>
  <a href="<%= edit_post_path(@post.hashed_key) %>">(edit)</a>
  <br>

  <hr>

  <!-- Post Body -->
  <div id="post-body-content">
    <%= raw(@post.body) %>
  </div>

  <!-- Reply Button -->
  <%= link_to 'Write Reply', new_post_path(reply: @post.hashed_key), class: 'button' %>

  <!-- Show replies -->
  <% unless @post.replies.empty? %>
    <br />
    <h5>Replies to this post: </h5>
      <% @post.replies.each do |r| %>
        <div class="panel">
          <%= link_to r.title, post_slug_path(r.hashed_key, r.title_slug) %>
        </div>
      <% end %>
  <% end %>

  <!-- Hidden Vote Form -->
  <%= form_tag post_vote_path, 
    method: :post, 
    remote: true, 
    authenticity_token: true, 
    format: :json,
    id: 'vote-form' do %>
  <% end %>

</div>

app/views/posts/signin.html.erb
<h1>Enter Password</h1>
<h4>Post: <%= @post.title %></h4>
<%= form_tag(post_authenticate_path(@post.hashed_key), method: 'post') do %>
  <%= password_field_tag :password, "", style: 'width: 200px;', placeholder: 'password' %>
  <%= submit_tag 'Submit', :class => 'button small success', style: 'display: inline' %>
<% end %>